version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: sddf-bench-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: benchmark_db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - benchmark-network

  mongo-express:
    image: mongo-express:latest
    container_name: sddf-bench-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpassword
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - benchmark-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - benchmark-network

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
    environment:
      - ENABLE_FILE_STORAGE=true
      - ENABLE_MONGODB_STORAGE=true
      - MONGODB_URI=mongodb://admin:adminpassword@mongodb:27017/benchmark_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - benchmark-network

volumes:
  mongodb_data:
  mongodb_config:

networks:
  benchmark-network:
    driver: bridge
